# Generated by Django 4.1.3 on 2022-11-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('details', models.TextField(blank=True, default='-', max_length=2000, null=True, verbose_name='Описание товара')),
                ('status', models.CharField(choices=[('other', 'Другое'), ('electronics', 'Электроника'), ('garden', 'Для сада'), ('food', 'Еда')], default='other', max_length=20, verbose_name='Статус')),
                ('balance', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
